/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.android.anddeche;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int blue_marker=0x7f020000;
        public static final int empty_bg=0x7f020001;
        public static final int icon=0x7f020002;
        public static final int info=0x7f020003;
        public static final int line=0x7f020004;
        public static final int marker_decheterie=0x7f020005;
        public static final int titre_menu=0x7f020006;
    }
    public static final class id {
        public static final int acceptesLayout=0x7f05000a;
        public static final int adresse=0x7f050003;
        public static final int btn10km=0x7f050017;
        public static final int btn20km=0x7f05001a;
        public static final int btn30km=0x7f05001d;
        public static final int btn45km=0x7f050020;
        public static final int btn5km=0x7f050014;
        public static final int btnInfo=0x7f050022;
        public static final int btnLienSinoe=0x7f050010;
        public static final int btnMore=0x7f050004;
        public static final int btnSYRendre=0x7f05000f;
        public static final int distance=0x7f050002;
        public static final int googlemapview=0x7f050023;
        public static final int horairesLayout=0x7f050005;
        public static final int imageTitre=0x7f050011;
        public static final int labelAcceptes=0x7f05000b;
        public static final int labelHoraires=0x7f050008;
        public static final int labelJoursOuverts=0x7f050006;
        public static final int labelRefuses=0x7f05000d;
        public static final int lignesous10km=0x7f050019;
        public static final int lignesous20km=0x7f05001c;
        public static final int lignesous30km=0x7f05001f;
        public static final int lignesous5km=0x7f050016;
        public static final int nom=0x7f050001;
        public static final int scrollViewDialog=0x7f050000;
        public static final int texte10km=0x7f050018;
        public static final int texte20km=0x7f05001b;
        public static final int texte30km=0x7f05001e;
        public static final int texte45km=0x7f050021;
        public static final int texte5km=0x7f050015;
        public static final int texteAcceptes=0x7f05000c;
        public static final int texteHoraires=0x7f050009;
        public static final int texteIntro=0x7f050012;
        public static final int texteJoursOuverts=0x7f050007;
        public static final int texteRayon=0x7f050013;
        public static final int texteRefuses=0x7f05000e;
        public static final int zoomcontrols=0x7f050024;
    }
    public static final class layout {
        public static final int dialogdechelayout=0x7f030000;
        public static final int mainlayout=0x7f030001;
        public static final int maplayout=0x7f030002;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
    }
}
